### ISSUE TITLE
train_network.py: error: unrecognized arguments: weight_decay=0.04

### ISSUE THREAD

**Issue by GeneralAwareness** [Linaqruf/kohya-trainer#111]
Can't use it.

![image](https://user-images.githubusercontent.com/124339252/222684542-e8010827-9e03-4067-9bc3-8f3efb219c9b.png)

**Comment by Linaqruf** [comment]
put inside a list, try ["weight_decay=0.6", "decouple=true"]

**Comment by GeneralAwareness** [comment]
> put inside a list, try ["weight_decay=0.6", "decouple=true"]

I am not sure how, or where to put it.  I know the gui version does work so I wonder if I have to clone to get the updated kohya scripts?

**Comment by GeneralAwareness** [comment]
train_network.py: error: unrecognized arguments: momentum=0.9

**Comment by Linaqruf** [comment]
main repo is doing a massive changes so it won't work for a while with notebook from this repo
and I don't think I will merge the latest updates because too much work to do, [#110 comment](https://github.com/Linaqruf/kohya-trainer/issues/110#issuecomment-1453301775)

For `optimizer_args` i'll try my best to fix it, i think i'll implement `yaml` or `toml` instead of shell script to wrap training args next time.

**Comment by GeneralAwareness** [comment]
The optimizer_args not working means this was published before testing to see if it actually works and a prior script is being used.

Can't wait to finally be able to use these.

Thanks again.

**Comment by GeneralAwareness** [comment]
I see why, I believe, this is not working

![image](https://user-images.githubusercontent.com/124339252/222921228-f1ca78fc-2b94-4d95-99e5-4b143435f8fd.png)

That should not be on its own it should be a space not a comma such as "--optimizer_args decouple=True weight_decay=0.04"

**Comment by GeneralAwareness** [comment]
Fixed this issue then a new issue happens as I got past the argv/argc issue (you can't pass a space as you did because it needs to be single quoted then it will know that is just one line) then I get the following error:

prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "train_network.py", line 507, in <module>
    train(args)
  File "train_network.py", line 150, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/content/drive/MyDrive/kohya-trainer/library/train_util.py", line 1551, in get_optimizer
    key, value = arg.split('=')
ValueError: too many values to unpack (expected 2)

Fix one find another only my colab is free so I can't work with this for too long per day.
