### ISSUE TITLE
<Signals.SIGKILL: 9> Error saving model as safetensors (kohya-dreambooth)

### ISSUE THREAD

**Issue by CristianMaza** [Linaqruf/kohya-trainer#118]
I trained a dreambooth model an hour ago. At the end of the training I got an error after "save trained model as StableDiffusion checkpoint to /content/dreambooth/output/sks.safetensors"
I think there was a folder in output with the diffuser files so I probably got the error while converting to safetensors.

I just noticed there is a new commit from a couple of minutes ago so I tried again with the latest notebook and I got the same error while saving but this time there's only a "sample" folder with the sample images (from which I can say the training was successful). 

This is the error output:

save trained model as StableDiffusion checkpoint to /content/dreambooth/output/sks.safetensors
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_db.py', '--sample_prompts=/content/dreambooth/config/sample_prompt.txt', '--dataset_config=/content/dreambooth/config/dataset_config.toml', '--config_file=/content/dreambooth/config/config_file.toml']' died with <Signals.SIGKILL: 9>.

Again, from the samples folder I can see that the training was successful but the model is not saved

**Comment by CristianMaza** [comment]
Update:
Selecting "save_model_as: ckpt" works just fine, the error happens if I select "safetensors" (which is selected by default)

**Comment by Linaqruf** [comment]
HI, i'm sorry for the problem, i made a temporary fix to 
1) load and save model in gpu for non lora notebook
2) set `.ckpt` as default value for `save_model_as`, but i think .safetensors will work again.
