### ISSUE TITLE
ERROR: xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by alinasama** [Linaqruf/kohya-trainer#125]
I have the error message with this then I can't use it during training.
ERROR: xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by GeneralAwareness** [comment]
BECAUSE, as Linaqruf said in a previous post Google was changing in a couple to three weeks and apparently they just changed Python versions.

![image](https://user-images.githubusercontent.com/124339252/223805065-18fbbe96-11d2-485e-8edc-198e75feb0b4.png)

**Comment by Iyashinouta** [comment]
you can change code  from this :

`  if install_xformers:
    if 'T4' in s:
      %pip -q install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.16/xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl
      !pip -q install --pre triton
    if 'A100' in s:
      %pip -q install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15+e163309.d20230103.ColabProA100-cp38-cp38-linux_x86_64.whl
`

to this : 

`  if install_xformers:
    if 'T4' in s:
      %pip -q install -U xformers
      !pip -q install --pre triton
    if 'A100' in s:
      %pip -q pip install -U xformers
`

I still running, and may work properly
![image](https://user-images.githubusercontent.com/126176394/223849242-12f5026d-d688-4c23-b35a-305b76c0ed44.png)

**Comment by GeneralAwareness** [comment]
> you can change code from this :
> 
> `%pip -q install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.16/xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl`
> 
> to this :
> 
> `%pip -q install -U xformers`
> 
> I still running, and may work properly ![image](https://user-images.githubusercontent.com/126176394/223849242-12f5026d-d688-4c23-b35a-305b76c0ed44.png)

Why did the notebook not have this to begin with instead of a static link if this works so well?

**Comment by Iyashinouta** [comment]
> Why did the notebook not have this to begin with instead of a static link if this works so well?

did you not scroll down to see the output?, I mean after pressing the Run button

**Comment by GeneralAwareness** [comment]
> > Why did the notebook not have this to begin with instead of a static link if this works so well?
> 
> did you not scroll down to see the output?, I mean after pressing the Run button

My point was why were static d/l links used instead of this method?  Yes, it works so it doesn't make sense to have static links if this works OR did this not work for Python 3.8.x?

**Comment by Iyashinouta** [comment]
> My point was why were static d/l links used instead of this method? Yes, it works so it doesn't make sense to have static links if this works OR did this not work for Python 3.8.x?

oh I'm sorry, maybe different types, I use fast training

**Comment by StableDiffusion123** [comment]
Sorry for the beginner question but where exactly should I be replacing this: %pip -q install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.16/xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl 

to this: %pip -q install -U xformers

in order to fix the issue?

**Comment by Iyashinouta** [comment]
> Sorry for the beginner question but where exactly should I be replacing the code in the aforementioned fix?
> 
> I was only able to find
> 
> if install_xformers: !pip -q install -U -I --no-deps https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15.dev0+189828c.d20221207-cp38-cp38-linux_x86_64.whl
> 
> which is not the same, right?

did you using Old Version?, just check Newer Version

**Comment by Iyashinouta** [comment]
> Yeah I am using the original version because the later ones were not working for me, but replacing the part I copy pasted with the fix seems to have done the trick regardless.

if you get an issue like that, try changing it as I mentioned earlier

**Comment by Linaqruf** [comment]
Hi, thank you for waiting. It should be fixed now. All 4main notebooks, as well as the Cagliostro Colab UI and Fast Kohya Trainer, should work. I used the pre-installed xformers from PyPI.

```python
    !pip install -q --pre xformers
    !pip install -q --pre triton
```
It should work for any GPU, including A100, and it won't break again when Colab updates its Python version to 3.10 in two or three months from now. (Probably, because Kohya wrote this training script in Python 3.10)

**Comment by 0me1** [comment]
> Hi, thank you for waiting. It should be fixed now. All 4main notebooks, as well as the Cagliostro Colab UI and Fast Kohya Trainer, should work. I used the pre-installed xformers from PyPI.
> 
> ```python
>     !pip install -q --pre xformers
>     !pip install -q --pre triton
> ```
> 
> It should work for any GPU, including A100, and it won't break again when Colab updates its Python version to 3.10 in two or three months from now. (Probably, because Kohya wrote this training script in Python 3.10)

Please fix old commit (Fine-tune method) colab too

**Comment by Linaqruf** [comment]
I can't help with old commit, you can manually install them with this code after `1.1. Install dependencies` cell

```python
!pip uninstall -y xformers
!pip install -q --pre xformers
!pip install -q --pre triton
```

I think you should try the latest one, the code more clean and you can generating sample every n epochs as well.
