### ISSUE TITLE
Fast Trainer VAE Dir syntax

### ISSUE THREAD

**Issue by kieranxsomer** [Linaqruf/kohya-trainer#127]
File ["<ipython-input-3-7ee032f74cc9>"](https://localhost:8080/#), line 33
    vae = os.path.join(root_dir, /vae")
                                 ^
SyntaxError: invalid syntax

**Comment by kieranxsomer** [comment]
OH extra issue in dreambooth lora trainer: the image zip keeps flipping out - it should be ok if you upload it and rename it to zipfile.zip but it's getting freaky cranky XD

**Comment by Linaqruf** [comment]
> OH extra issue in dreambooth lora trainer: the image zip keeps flipping out - it should be ok if you upload it and rename it to zipfile.zip but it's getting freaky cranky XD

Hi, can u explain more about this?

**Comment by Linaqruf** [comment]
I'm fixed the issue
