### ISSUE TITLE
why im getting this?

### ISSUE THREAD

**Issue by riade3788** [Linaqruf/kohya-trainer#128]
Downloading...
From: https://drive.google.com/uc?id=1TINXq-us2aUC5d1lCXGITP4yjzmA-IHY
To: /content/10_Mate.zip
100% 3.19M/3.19M [00:00<00:00, 205MB/s]
unzip:  cannot find or open /content/zipfile.zip, /content/zipfile.zip.zip or /content/zipfile.zip.ZIP.

---------------------------------------------------------------------------

FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-17-0dc577f0c388>](https://localhost:8080/#) in <module>
     37 if not zipfile_url.startswith("/content"):
     38   get_ipython().system('unzip -j -o "{root_dir}/{zipfile_name}" -d "{unzip_to}"')
---> 39   os.remove(f"{root_dir}/{zipfile_name}")
     40 
     41 files_to_move = ("meta_cap.json", \

FileNotFoundError: [Errno 2] No such file or directory: '/content/zipfile.zip'

**Comment by kieranxsomer** [comment]
Yep ok so just go to your file listing on the side - and rename the zip file to zipfile.zip - its' annoying but it WORKS trust me XD

**Comment by Linaqruf** [comment]
Hi, may i know which notebook is this?
