### ISSUE TITLE
Cannot use lycoris.lora

### ISSUE THREAD

**Issue by nothelloearth1** [Linaqruf/kohya-trainer#130]
import network module: lycoris.kohya
Traceback (most recent call last):
  File "/content/kohya-trainer/train_network.py", line 663, in <module>
    train(args)
  File "/content/kohya-trainer/train_network.py", line 144, in train
    key, value = net_arg.split('=')
ValueError: not enough values to unpack (expected 2, got 1)

I got this error with both "algo=lora" and "algo=loha".

**Comment by Linaqruf** [comment]
put inside a square bracket or a list
["algo=loha","conv_dim=16","conv_alpha=1"]

**Comment by nothelloearth1** [comment]
It's working now, finally.

I think this line
> For custom networks_module you need to set additional network_args, e.g.: ["conv_dim=32","conv_alpha=16"]

should be rephrased as

> For lycoris.kohya you need to set additional network_args, e.g.: ["conv_dim=32","conv_alpha=16"]
to avoid any further confusion.

Anyway, thank you for your hard work and have a good day.
