### ISSUE TITLE
Step 5.5 Error "name 'sample_every_n_type' is not defined"

### ISSUE THREAD

**Issue by Coffeelatte369** [Linaqruf/kohya-trainer#137]
Hi, this afternoon i just train some dataset and it went well, but suddenly it's error when i tried to trained another one. Can someone help me? I followed the tutorial from here https://www.youtube.com/watch?v=ddpaECgRCHg, it worked well at first, but i dont know what happened now it's said error.

First image is the error and second one is the setting i used. Thanks in advance.

<img width="779" alt="1" src="https://user-images.githubusercontent.com/111590878/225335089-151b04a3-1494-4aa9-8592-3f9b36ccb3f1.png">
<img width="239" alt="2" src="https://user-images.githubusercontent.com/111590878/225335265-5aac73fb-0f43-4ab4-a666-41413fc25ea9.png">

**Comment by Linaqruf** [comment]
Hi, i think you're forgot to run `5.3. Sample Prompt Config`

**Comment by Coffeelatte369** [comment]
Yes! Forgive me for my clueless and careless, it's working now. You can close this issue now, thanks!
