### ISSUE TITLE
Fresh install error: xformers is not supported wheel on this platform

### ISSUE THREAD

**Issue by tommyjohn81** [Linaqruf/kohya-trainer#140]
in the first step of the [dreambooth lora colab](https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/dev/kohya-LoRA-dreambooth.ipynb?), install dependencies:

**ERROR: xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.**

code:
def install_dependencies():
  !pip -q install --upgrade gallery-dl gdown imjoy-elfinder ruamel.yaml dadaptation lion-pytorch "locon==0.0.3"
  !pip -q install --upgrade -r requirements.txt

  s = getoutput('nvidia-smi')
  if install_xformers:
    if 'T4' in s:
      %pip -q install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.16/xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl
      !pip -q install --pre triton
    if 'A100' in s:
      %pip -q install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15+e163309.d20230103.ColabProA100-cp38-cp38-linux_x86_64.whl

**Comment by Linaqruf** [comment]
Hi, you're using old commit, I can't help but suggests to :
1. Use newer version of the notebook
2. Manually install newer xformers 
```
!pip uninstall -y xformers
!pip install -q --pre xformers
!pip install -q --pre triton
```
