### ISSUE TITLE
Dependencies conflict after new update

### ISSUE THREAD

**Issue by Norian11** [Linaqruf/kohya-trainer#144]
Well in the Kohya Lora Dreambooth in the first cell creates an error that says that many dependencies need Torch 1.13.1 but i have 2.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.14.1+cu116 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
torchtext 0.14.1 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
fastai 2.7.11 requires torch<1.14,>=1.7, but you have torch 2.0.0 which is incompatible.

Edit: It seems to works fine anyways

**Comment by sumof2primes** [comment]
triton pre-release updated and 2.0.0 released. 

change 
!pip install -q --pre triton
to
!pip install -q triton

**Comment by noriwaru** [comment]
I changed it to "!pip install -q triton" but I get the same error. The training itself is working.

**Comment by Linaqruf** [comment]
use this
```
!pip install -q xformers=="0.0.17.dev476"
!pip install -q triton=="2.0.0.post1"
```
Temporary fix until colab officially updating pytorch to 2.0 https://github.com/googlecolab/colabtools/issues/3503
