### ISSUE TITLE
"NameError: name 'train_data_dir' is not defined " error in kohya-LoRA-dreambooth colab

### ISSUE THREAD

**Issue by BahzBeih** [Linaqruf/kohya-trainer#149]
Hi i got this error message when trying to extract dataset zip with "Unzip Dataset" form,  in  kohya-LoRA-dreambooth colab

NameError                                 Traceback (most recent call last)
<ipython-input-23-2b2299bcb5b3> in <module>
     17     os.makedirs(unzip_to, exist_ok=True)
     18 else:
---> 19     unzip_to = train_data_dir
     20 
     21 

NameError: name 'train_data_dir' is not defined

**Comment by Linaqruf** [comment]
Hi, i think you forgot to run this cell, hope this help
![image](https://user-images.githubusercontent.com/50163983/226824063-3b4fadfc-90ac-4f1e-8ea7-c24cc90e250c.png)

**Comment by BahzBeih** [comment]
i just figured it out and i was going to close the issue, thanks for your help.
