### ISSUE TITLE
Train Model has an error

### ISSUE THREAD

**Issue by Lookatme5555** [Linaqruf/kohya-trainer#15]
I trained a model and after training I tried to test it on Stable Diffusion it gives me that error. How do I fix it? 

![Error 1](https://user-images.githubusercontent.com/109504885/210286138-910a00bd-d12a-4eda-8472-3394e49f28ff.PNG)

**Comment by Lookatme5555** [comment]
Hey thanks for the reply! Sorry I didnt include more information but yea I think it is Waifu DIff 1.4 finetuned. I used ur default settings in the colab. Only thing I change is the "Install Pretrained model" part where I put SD1 as anythingv3pruned and edit "Training Begin" save_model_as: default. But yeah I will install the v2-inference.yaml when I get home and I will put my results here later.

**Comment by Lookatme5555** [comment]
Holy crap it works!!! Thanks Linaqruf for the solution mate!!! Really appreciate!

**Comment by Linaqruf** [comment]
yeah no problem
