### ISSUE TITLE
Could not find a version that satisfies the requirement xformers

### ISSUE THREAD

**Issue by dink12k** [Linaqruf/kohya-trainer#151]
when i run it show error
ERROR: Could not find a version that satisfies the requirement xformers==0.0.17.dev476 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7 , 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17.dev480, 0.0.17.dev481, 0.0 .17.dev482, 0.0.17.dev483, 0.0.17.dev484, 0.0.17rc481, 0.0.17rc482)
ERROR: No matching distribution found for xformers==0.0.17.dev476
how to fix it

**Comment by ToroLing** [comment]
me too

**Comment by hollowstrawberry** [comment]
I fixed it by editing this part of the installation:

```py
def install_dependencies():
    !pip -q install --upgrade -r requirements.txt

    if install_xformers:
        !pip install -q xformers=="0.0.17.dev476"
        !pip install -q triton=="2.0.0.post1"

    from accelerate.utils import write_basic_config

    if not os.path.exists(accelerate_config):
        write_basic_config(save_location=accelerate_config)


os.chdir(repo_dir)
!apt -y update -qq
ubuntu_deps(
    "https://huggingface.co/Linaqruf/fast-repo/resolve/main/ram_patch.zip", 
    "ram_patch.zip", 
    deps_dir,
)
%env LD_PRELOAD=libtcmalloc.so
ubuntu_deps(
    "https://huggingface.co/Linaqruf/fast-repo/resolve/main/deb-libs.zip",
    "deb-libs.zip",
    deps_dir,
)
install_dependencies()```

to:

```py
def install_dependencies():
    !pip install torch==2.0.0+cu118 torchvision --extra-index-url https://download.pytorch.org/whl/cu118
    !pip -q install --upgrade -r requirements.txt
    !pip install -q xformers=="0.0.17.dev480"
    !pip install -q triton=="2.0.0.post1"

    from accelerate.utils import write_basic_config
    if not os.path.exists(accelerate_config):
        write_basic_config(save_location=accelerate_config)

os.chdir(repo_dir)
!apt -y update -qq
!apt install libunwind8=1.2.1-9build1
ubuntu_deps(
    "https://huggingface.co/Linaqruf/fast-repo/resolve/main/ram_patch.zip", 
    "ram_patch.zip", 
    deps_dir,
)
%env LD_PRELOAD=libtcmalloc.so
ubuntu_deps(
    "https://huggingface.co/Linaqruf/fast-repo/resolve/main/deb-libs.zip",
    "deb-libs.zip",
    deps_dir,
)
install_dependencies()
```

**Comment by ToroLing** [comment]
I changed the "if install_xformers:"
```
def install_dependencies():
    !pip -q install --upgrade -r requirements.txt

    if install_xformers:
        !pip install -q xformers
        !pip install -q triton=="2.0.0.post1"

    from accelerate.utils import write_basic_config

    if not os.path.exists(accelerate_config):
        write_basic_config(save_location=accelerate_config)
```

**Comment by hollowstrawberry** [comment]
Did that also work?

I had also added another fix where `ram_patch.zip` needed `libunwind8=1.2.1-9build1`

**Comment by hypernewb** [comment]
I just ran pip install xformers==0.0.17rc482
and it worked

**Comment by Linaqruf** [comment]
They are removing `0.0.17.dev476` wheels, and I don't understand why. https://pypi.org/project/xformers/#history.

All 0.0.17 xformers will automatically install `torch 2.0.0` and triton `2.0.0` from now on. We will revert back to version 0.0.16 until colabtools officially installs pytorch 2.0.

**Comment by Linaqruf** [comment]
pushed the fix, 
![image](https://user-images.githubusercontent.com/50163983/227490816-bc19e075-88f3-409b-b572-ca68f7181f89.png)

**Comment by hollowstrawberry** [comment]
> pushed the fix

It seems the trainer is fucked now, all my loras come out fried with the same settings I've always used

**Comment by hollowstrawberry** [comment]
![](https://media.discordapp.net/attachments/1088905841819779114/1088913486807060511/xyz_grid-0003-1.png)

**Comment by hollowstrawberry** [comment]
It seems I had a problem with my generation parameters which I'm having a hard time finding the source of. But for now please disregard my last 2 messages
