### ISSUE TITLE
Help wanted. Not getting good results.

### ISSUE THREAD

**Issue by JasonS09** [Linaqruf/kohya-trainer#152]
Hello. I have been attempting to train a 2.1 LoRA based on SD 2.1 768 model. However, I never get good results. And what I mean with this is that my trained LoRAs are not working at all in the sense they don’t seem to be affecting generation outputs, or they just output some random noise. I think I'm doing something wrong, so I'm going to list the things I suspect might be the cause.

1) Input images: I'm training the model using 24 input images of screenshots of a videogame character of an special fantasy race. Images are captioned, and in all the captions the keyword "bnck" is present. "Bnck" is the value I use for project name, which I understand is the trigger word for the subject. Am I getting this right?

2) I'm training the 24 input images on 6 epochs of 25 reps, 2 batches. Rest of the config values are the defaulted ones. All images are 768x768.

3) All preview images during training are fried like this:
![bnck_20230324011647_e000005_00](https://user-images.githubusercontent.com/47617351/227429246-abe5ff85-6eb4-4e03-9254-beca108865c0.png)

Note that this isn't my character at all. Images have normal quality when I use the webui though, but my character is still not present. I know 2.1 LoRAs are not supported for Automatic1111, but when I try to use the extension to load it, I instead get a blank image (it's actually brown, but it's totally empy).

The sample prompt I'm using is something like:

"Digital painting of a close up of the face of bnck, looking at viewer, front view, green eyes". When the LoRA isn't loaded this returns the face of a random person (like the one in the image I uploaded). When it is loaded, it just simply returns the noise.

I recently trained a model using dreambooth and it worked. It's LoRAs that are giving me this issue. It's like my third attempt but I always get the same results.

**Comment by hollowstrawberry** [comment]
My loras come out deepfried too

**Comment by rewixx** [comment]
my too

**Comment by Linaqruf** [comment]
Mind to share LoRA metadata or training `config_file.toml`?
1. If you train SD 2.1 768v, you must set `both--v2` and `--v_parameterization` to `True`
2. SDv2 based LoRA still not supported in Web UI
3. You only can use `LoCon_Lycoris` and `LoHa` using built-in Web UI LoRA (requires: [a1111-sd-webui-locon](https://github.com/KohakuBlueleaf/a1111-sd-webui-locon) extension)
4. You only can use `LoCon` trained with `networks.lora` in [sd-webui-additional-networks](https://github.com/kohya-ss/sd-webui-additional-networks) extension, AFAIK

**Comment by JasonS09** [comment]
Thanks for the info, I'll take note of it next time I want to train a 2.1 LoRA. I'll train a normal checkpoint instead because I need to work from the API and I think I can't use extensions that way.
