### ISSUE TITLE
why it generates latent nothing 

### ISSUE THREAD

**Issue by rewixx** [Linaqruf/kohya-trainer#155]
if i lower the weigt it's les like latent nothing 
![grid-0003](https://user-images.githubusercontent.com/106181044/227647447-95205a5b-01a3-47c8-a783-05cf1066142b.png)
![grid-0002](https://user-images.githubusercontent.com/106181044/227647460-8a8c6784-0714-46dd-a4d6-2bd349e32523.png)
![grid-0000 (1)](https://user-images.githubusercontent.com/106181044/227647624-7e36dd4d-bee3-4231-b4c1-fab7a6b7345b.png)

**Comment by Linaqruf** [comment]
Can u give more information? like the training `config_file.toml`? or metadata.

**Comment by rewixx** [comment]
i was using this version https://colab.research.google.com/drive/1s6Nz7DqHY1bluVF-nBRIvnFeHpuLrj0w

**Comment by rewixx** [comment]
the version of the colab that i use dosen't have   config_file.toml files

**Comment by rewixx** [comment]
ok i fixed it 

![grid-0005 (2)](https://user-images.githubusercontent.com/106181044/227722850-7b3e7754-a664-4ae9-b2f6-154ae92b0c0c.png)

used old version
