### ISSUE TITLE
Error after using new version

### ISSUE THREAD

**Issue by duonglexxx** [Linaqruf/kohya-trainer#156]
hello, thanks for your great work..

CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', 
'--sample_prompts=/content/LoRA/config/sample_prompt.txt', 
'--dataset_config=/content/LoRA/config/dataset_config.toml', 
'--config_file=/content/LoRA/config/config_file.toml']' returned non-zero exit 
status 1.

**Comment by Linaqruf** [comment]
Hello, can you explain more?

**Comment by gitaiuser20** [comment]
im getting the same issue, how did you fix it ?
