### ISSUE TITLE
Dependacy incompatibility

### ISSUE THREAD

**Issue by bemyak** [Linaqruf/kohya-trainer#162]
Hi!

When installing deps with xformers, I'm getting the following error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.14.1+cu116 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
torchtext 0.14.1 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
fastai 2.7.11 requires torch<1.14,>=1.7, but you have torch 2.0.0 which is incompatible.
```

Is there any workaround for this, please?

**Comment by CeterPushing** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.14.1+cu116 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
torchtext 0.14.1 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 2.0.0 which is incompatible.
fastai 2.7.11 requires torch<1.14,>=1.7, but you have torch 2.0.0 which is incompatible.

Same issue is there another branch we can use that is working?

**Comment by cczhong11** [comment]
install_xformers=False to skip install xformers works for me.

**Comment by bemyak** [comment]
Thanks! It works now, the training is reachable now.

However, there is still an incompatibility when trying to deploy to ngrok:
```
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.6. Please reinstall the torchvision that matches your PyTorch install.
```

**Comment by bemyak** [comment]
And when running step 6.3, I'm getting this:
```
python3: can't open file '/content/stable-diffusion-webui/gen_img_diffusers.py': [Errno 2] No such file or directory

```

**Comment by Linaqruf** [comment]
Thank you for the suggestion, I forgot to set os.chdir(repo_dir). I use your fix to inference cell in the latest update.
