### ISSUE TITLE
Training Config :  Use of Bf16

### ISSUE THREAD

**Issue by Rudy34160** [Linaqruf/kohya-trainer#169]
Test of use in the Colab: https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb?authuser=0#scrollTo=p_SHtbFwHVl1

Option available in "Training Config" but in error afterwards? 🤔
Bad settings on my part?

![image](https://user-images.githubusercontent.com/118270456/228805174-0758b7ae-5cca-4cb8-959a-ed69db1f4534.png)

![image](https://user-images.githubusercontent.com/118270456/228805231-c9e62806-0c50-42c8-8d6a-0a0de2a3b94d.png)

**Comment by GeneralAwareness** [comment]
T4 doesn't have BF16 anyway.
