### ISSUE TITLE
Dadaption will not work using the latest notebook

### ISSUE THREAD

**Issue by GeneralAwareness** [Linaqruf/kohya-trainer#170]
prepare optimizer, data loader etc.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/kohya-trainer/train_network.py:693 in <module>                      │
│                                                                              │
│   690 │   args = parser.parse_args()                                         │
│   691 │   args = train_util.read_config_from_file(args, parser)              │
│   692 │                                                                      │
│ ❱ 693 │   train(args)                                                        │
│   694                                                                        │
│                                                                              │
│ /content/kohya-trainer/train_network.py:183 in train                         │
│                                                                              │
│   180 │   print("prepare optimizer, data loader etc.")                       │
│   181 │                                                                      │
│   182 │   trainable_params = network.prepare_optimizer_params(args.text_enco │
│ ❱ 183 │   optimizer_name, optimizer_args, optimizer = train_util.get_optimiz │
│   184 │                                                                      │
│   185 │   # dataloaderを準備する                                             │
│   186 │   # DataLoaderのプロセス数：0はメインプロセスになる                  │
│                                                                              │
│ /content/kohya-trainer/library/train_util.py:2151 in get_optimizer           │
│                                                                              │
│   2148 │   if args.optimizer_args is not None and len(args.optimizer_args) > │
│   2149 │   │   for arg in args.optimizer_args:                               │
│   2150 │   │   │   key, value = arg.split("=")                               │
│ ❱ 2151 │   │   │   value = ast.literal_eval(value)                           │
│   2152 │   │   │                                                             │
│   2153 │   │   │   # value = value.split(",")                                │
│   2154 │   │   │   # for i in range(len(value)):                             │
│                                                                              │
│ /usr/lib/python3.9/ast.py:105 in literal_eval                                │
│                                                                              │
│    102 │   │   │   │   else:                                                 │
│    103 │   │   │   │   │   return left - right                               │
│    104 │   │   return _convert_signed_num(node)                              │
│ ❱  105 │   return _convert(node_or_string)                                   │
│    106                                                                       │
│    107                                                                       │
│    108 def dump(node, annotate_fields=True, include_attributes=False, *, ind │
│                                                                              │
│ /usr/lib/python3.9/ast.py:104 in _convert                                    │
│                                                                              │
│    101 │   │   │   │   │   return left + right                               │
│    102 │   │   │   │   else:                                                 │
│    103 │   │   │   │   │   return left - right                               │
│ ❱  104 │   │   return _convert_signed_num(node)                              │
│    105 │   return _convert(node_or_string)                                   │
│    106                                                                       │
│    107                                                                       │
│                                                                              │
│ /usr/lib/python3.9/ast.py:78 in _convert_signed_num                          │
│                                                                              │
│     75 │   │   │   │   return + operand                                      │
│     76 │   │   │   else:                                                     │
│     77 │   │   │   │   return - operand                                      │
│ ❱   78 │   │   return _convert_num(node)                                     │
│     79 │   def _convert(node):                                               │
│     80 │   │   if isinstance(node, Constant):                                │
│     81 │   │   │   return node.value                                         │
│                                                                              │
│ /usr/lib/python3.9/ast.py:69 in _convert_num                                 │
│                                                                              │
│     66 │   │   raise ValueError(f'malformed node or string: {node!r}')       │
│     67 │   def _convert_num(node):                                           │
│     68 │   │   if not isinstance(node, Constant) or type(node.value) not in  │
│ ❱   69 │   │   │   _raise_malformed_node(node)                               │
│     70 │   │   return node.value                                             │
│     71 │   def _convert_signed_num(node):                                    │
│     72 │   │   if isinstance(node, UnaryOp) and isinstance(node.op, (UAdd, U │
│                                                                              │
│ /usr/lib/python3.9/ast.py:66 in _raise_malformed_node                        │
│                                                                              │
│     63 │   if isinstance(node_or_string, Expression):                        │
│     64 │   │   node_or_string = node_or_string.body                          │
│     65 │   def _raise_malformed_node(node):                                  │
│ ❱   66 │   │   raise ValueError(f'malformed node or string: {node!r}')       │
│     67 │   def _convert_num(node):                                           │
│     68 │   │   if not isinstance(node, Constant) or type(node.value) not in  │
│     69 │   │   │   _raise_malformed_node(node)                               │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: malformed node or string: <ast.Name object at 0x7f34199bd6a0>
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/bin/accelerate:8 in <module>                                      │
│                                                                              │
│   5 from accelerate.commands.accelerate_cli import main                      │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(main())                                                     │
│   9                                                                          │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py │
│ :45 in main                                                                  │
│                                                                              │
│   42 │   │   exit(1)                                                         │
│   43 │                                                                       │
│   44 │   # Run                                                               │
│ ❱ 45 │   args.func(args)                                                     │
│   46                                                                         │
│   47                                                                         │
│   48 if __name__ == "__main__":                                              │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py:1104 in │
│ launch_command                                                               │
│                                                                              │
│   1101 │   elif defaults is not None and defaults.compute_environment == Com │
│   1102 │   │   sagemaker_launcher(defaults, args)                            │
│   1103 │   else:                                                             │
│ ❱ 1104 │   │   simple_launcher(args)                                         │
│   1105                                                                       │
│   1106                                                                       │
│   1107 def main():                                                           │
│                                                                              │
│ /usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py:567 in  │
│ simple_launcher                                                              │
│                                                                              │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                  │
│    565 │   process.wait()                                                    │
│    566 │   if process.returncode != 0:                                       │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.return │
│    568                                                                       │
│    569                                                                       │
│    570 def multi_gpu_launcher(args):                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', 
'--sample_prompts=/content/LoRA/config/sample_prompt.txt', 
'--dataset_config=/content/LoRA/config/dataset_config.toml', 
'--config_file=/content/LoRA/config/config_file.toml']' returned non-zero exit 
status 1.

  - Using DAdaptation as Optimizer
  - Optimizer Args: ["decouple=true","weight_decay=0.6"]
  - Train UNet and Text Encoder
    - UNet learning rate: 1
    - Text encoder learning rate: 1
  - Learning rate warmup steps: 0

**Comment by Toshik-One** [comment]
today there was the same problem, I tried to reinstall but no effect was given (

**Comment by Linaqruf** [comment]
Hi, it's working, but I'm sorry because I provided a typo in the example for `network_args`. The correct option is `decouple=True`, not `decouple=true.`

![image](https://user-images.githubusercontent.com/50163983/229273547-3ac61b5f-2363-4209-b043-018f70f75e9b.png)
![image](https://user-images.githubusercontent.com/50163983/229273825-03e44680-7fba-4156-8908-37bbe21e74a4.png)

**Comment by GeneralAwareness** [comment]
Oh?  True needed to be in a Capital first letter?  How strange.
