### ISSUE TITLE
problem with training wd 1.4

### ISSUE THREAD

**Issue by Michaelwhite34** [Linaqruf/kohya-trainer#18]
train_db.py: error: unrecognized arguments: --v2_parameterization
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_db.py', '--v2', '--v2_parameterization', '--pretrained_model_name_or_path=/content/pre_trained_model/waifu-diffusion-1-4-anime-e-1.ckpt', '--train_data_dir=/content/dreambooth/train_1girl', '--reg_data_dir=/content/dreambooth/reg_1girl', '--output_dir=/content/drive/MyDrive/dreambooth1', '--prior_loss_weight=1.0', '--resolution=768', '--save_precision', 'fp16', '--train_batch_size=4', '--learning_rate=2e-6', '--max_train_steps=15000', '--use_8bit_adam', '--xformers', '--mixed_precision=fp16', '--gradient_checkpointing', '--save_every_n_epochs=50', '--enable_bucket', '--cache_latents', '--save_model_as', 'ckpt', '--shuffle_caption', '--caption_extension', '=.txt', '--save_state', '--logging_dir=/content/kohya-trainer/logs', '--log_prefix', 'dreambooth-style-sunori']' returned non-zero exit status 2.

**Comment by Michaelwhite34** [comment]
if I change v2_parameterization to v_parameterization, it gives the error

FATAL: this function is for sm80, but was built for sm750

**Comment by Linaqruf** [comment]
you can't use --v_parameterization to finetune wd.14 because the devs are using`sd 2.1 base` and not `sd 2.1 768v` as pretrained model, so you need to input --v2 only

**Comment by Michaelwhite34** [comment]
> you can't use --v_parameterization to finetune wd.14 because the devs are using`sd 2.1 base` and not `sd 2.1 768v` as pretrained model, so you need to input --v2 only

Thanks
