### ISSUE TITLE
no metadata / メタデータファイルがありません: meta_lat.json

### ISSUE THREAD

**Issue by Gyro0o** [Linaqruf/kohya-trainer#2]
![bandicam 2022-11-28 21-04-10-644](https://user-images.githubusercontent.com/117460296/204370514-e91711fc-58e6-474b-a7b5-f1066ca524e0.png)

When I start the training I get this error

**Comment by Linaqruf** [comment]
maybe you missed to run this cell, 
![image](https://user-images.githubusercontent.com/50163983/204412045-89c39ce1-2d6c-4839-88ff-d7376c058764.png)

this cell will create a file called meta_lat.json based on meta_cap_dd.json

```
!python prepare_buckets_latents.py train_data meta_cap_dd.json meta_lat.json {model_dir} \
  --batch_size {batch_size} \
  --max_resolution {max_resolution} \
  --mixed_precision {mixed_precision}
```

**Comment by Gyro0o** [comment]
![bandicam 2022-11-29 17-52-30-134](https://user-images.githubusercontent.com/117460296/204592260-f3e78013-6743-4574-8419-1dd4b2ee0d3f.png)
![bandicam 2022-11-29 17-52-41-340](https://user-images.githubusercontent.com/117460296/204592280-cc81228c-59c8-432a-8ef9-75fa41370561.png)

Yep I did 
I did upload my own images for training is that the problem
and what is the proper way to do it?

**Comment by Linaqruf** [comment]
You forgot to generate meta_cap_dd.json, it's a cell above novelai aspect bucketing cell
