### ISSUE TITLE
The scirpt you used in Section 4.2 is fed with wrong args.

### ISSUE THREAD

**Issue by zschaoihen** [Linaqruf/kohya-trainer#215]
When you invoke the "Waifu Diffusion 1.4 Tagger V2", the command you're current using is this:

python tag_images_by_wd14_tagger.py \
    "{train_data_dir}" \
    --batch_size {batch_size} \
    --repo_id {model} \
    --thresh {threshold} \
    --caption_extension .txt \
    --max_data_loader_n_workers {max_data_loader_n_workers}

But the thresh args will not work since it only takes either a general threshold or a character threshold.
![image](https://user-images.githubusercontent.com/29272145/234888413-31871368-d5ec-4e75-b4e6-72fdb01a317d.png)

**Comment by Linaqruf** [comment]
which notebook? 

{threshold} are from old notebook

**Comment by zschaoihen** [comment]
Oh, I must use the old version of LoRA_Dreambooth, but I think it will automatically pull the latest git repo, that's why I cannot make section 4.2 work.
