### ISSUE TITLE
How to Resume Training

### ISSUE THREAD

**Issue by Quadragonsaurus** [Linaqruf/kohya-trainer#22]
(INDONESIAN)

Halo kak, aku pengen resume training tapi masih bingung soal Pre-Trained Model yang harus dipakai buat resume, sebelumnya pakai AnythingV3-Pruned terus buat 10000 Steps, buat resume mending make last.ckpt atau AnythingV3-Pruned lagi terus dikasih folder last-state nya?

Btw kalo boleh minta ID Discord kakak dong, pengen tanya-tanya

(ENGLISH)
Hello I want a training resume but am still confused about the Pre-Trained Model that should be used for the resume, previously used AnythingV3-Pruned and then made 10000 Steps, for the resume is it better to make last.ckpt or AnythingV3-Pruned again and then give the last-state folder?

Btw, if I may ask for your Discord ID, I want to ask questions.

**Comment by dill-shower** [comment]
> Option 1 (loading the pretrained model and the last-state) is useful when you want to reproduce results or continue training a model that was performing well.

Hello.  Suppose I train a stable-diffusion model and name the training result Stabletune.ckpt and state folder. Made 10 epoch, got stabletune.ckpt file. For this training method (as I understand it is the best one), I need to specify the resume directory with the state of the optimizer and the rest, but how should the training model specify the original stable diffusion model and not stabletune.ckpt (result 10 epoch)?
