### ISSUE TITLE
Is there a way to hide the metadata? 

### ISSUE THREAD

**Issue by wzgrx** [Linaqruf/kohya-trainer#267]
When creating a LoRA, you don't want to include metadata information in the LoRA.
Is it possible to hide metadata in the colab?

If it is possible, in which item and what command should I use?

**Comment by taxen** [comment]
Is metadata included in generated images? I am struggling to recover the prompt I used to create the images and it seems there is no metadata related to the info. If such info is included, please tell me how to recover/show it. Thank you.
