### ISSUE TITLE
How to make grayscale?

### ISSUE THREAD

**Issue by ANIWAIFUS** [Linaqruf/kohya-trainer#278]
Hello, i started make a my personal project, and i need, that architecture model, generate only grayscale pictures on output, as pretrained model i using a anything_v3.1.

Will be glad, if you'll help me!

**Comment by younyokel** [comment]
Make the training data greyscale

**Comment by ANIWAIFUS** [comment]
Ah, ok, thanks.
Before, i thought that i need to write some parameters for layers.
