### ISSUE TITLE
Adafactor - IndexError: list index out of range

### ISSUE THREAD

**Issue by rayshan** [Linaqruf/kohya-trainer#296]
When using this optimizer config:

<img width="906" alt="Screenshot 2023-09-13 at 8 31 32 PM" src="https://github.com/Linaqruf/kohya-trainer/assets/3760840/4686e04c-abf1-46cd-bf43-508bedf60beb">

I get this error:
<img width="860" alt="Screenshot 2023-09-13 at 10 01 30 PM" src="https://github.com/Linaqruf/kohya-trainer/assets/3760840/d227e32e-8ae1-4271-b193-8e6a7495fd5e">

I think when I hit [this line](https://github.com/Linaqruf/kohya-trainer/blob/main/library/train_util.py#L2595), `name === 'adafactor'`, so it cannot be split. I think learning rate was supposed to be appended to the string [in this line](https://github.com/Linaqruf/kohya-trainer/blob/main/library/train_util.py#L2496C23-L2496C23) but it didn't.

Recommendation: store values in variables instead of manipulating strings.

**Comment by Linaqruf** [comment]
You can't use adafactor scheduler if relative_step is False

I suggest to stick with constant with warmup

**Comment by rayshan** [comment]
Got it, thank you!
