### ISSUE TITLE
Hope to add augmentation

### ISSUE THREAD

**Issue by OolongFox** [Linaqruf/kohya-trainer#3]
https://note.com/kohya_ss/n/nad3bce9a3622
I found that kohya has written face crop, color and flip augmentation, can you add it to colab please?

Here is another similar project: https://github.com/bmaltais/kohya_ss

**Comment by Linaqruf** [comment]
haven't tried the dreambooth yet, but that's a good idea, maybe I'll write it in a different notebook.

**Comment by Linaqruf** [comment]
Hi, I'm adapted kohya dreambooth up to v12 and also added the augmentation function 
https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-dreambooth-beta.ipynb

For Diffuser fine-tune sadly there is no augmentation function found in the fine-tune.py, so it's limited to dreambooth only.

but you can try the newer version of kohya trainer here :
https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-trainer-v3-beta.ipynb

**Comment by OolongFox** [comment]
> Hi, I'm adapted kohya dreambooth up to v12 and also added the augmentation function https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-dreambooth-beta.ipynb
> 
> For Diffuser fine-tune sadly there is no augmentation function found in the fine-tune.py, so it's limited to dreambooth only.
> 
> but you can try the newer version of kohya trainer here : https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-trainer-v3-beta.ipynb

Thanks a lot. Kohya says dreambooth is about equal to fine-tune without using prior_preservation and train_text_encoder.
