### ISSUE TITLE
New error while running on Colab since today

### ISSUE THREAD

**Issue by DreamCloudWalker** [Linaqruf/kohya-trainer#332]
mean ar error (without repeats): 0.006993006993007034
prepare accelerator

ValueError: fp16 mixed precision requires a GPU

CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', 
'--sample_prompts=/content/LoRA/config/sample_prompt.txt', 
'--dataset_config=/content/LoRA/config/dataset_config.toml', 
'--config_file=/content/LoRA/config/config_file.toml']' returned non-zero exit status 1.

**Comment by asahi0416** [comment]
I also encountered the same error. Could you please tell me the solution?

**Comment by DreamCloudWalker** [comment]
My fault, the real reason is this error : load Diffusers pretrained models
model is not found as a file or in Hugging Face, perhaps file name is wrong? 
My default safetensors download failed, after I change the safetensors link, it works fine!
