### ISSUE TITLE
FATAL: this function is for sm80, but was built for sm750

### ISSUE THREAD

**Issue by treksis** [Linaqruf/kohya-trainer#34]
Hi, I'm using colab pro with premium. 

I had this error but once I got rid of what was inside the additional_argument, it worked.

```
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
FATAL: this function is for sm80, but was built for sm750
```

<img width="321" alt="image" src="https://user-images.githubusercontent.com/54779707/214474075-870adf6c-26d7-4ad1-a611-64bd710109f0.png">

I see another round of this errors when I try to inference it, but no idea how to fix it. Is this xformers related??

<img width="288" alt="image" src="https://user-images.githubusercontent.com/54779707/214474277-4d8aa8cc-26cf-47d6-b27e-dce97c6c55ae.png">

**Comment by Linaqruf** [comment]
hello, xformers in the notebook is intended for T4 GPU, so it's incompatible with another GPU.
You need to built your own xformers or you can find it in internet

like this one https://github.com/TheLastBen/fast-stable-diffusion/tree/main/precompiled
