### ISSUE TITLE
LoRA-trainer-XL not working

### ISSUE THREAD

**Issue by noriwaru** [Linaqruf/kohya-trainer#345]
With free colab it does not work. Do I have to wait until they fix it?　I am very sad.

**Comment by gjlll4137** [comment]
Does not work too

**Comment by DEX-1101** [comment]
i change xformers to `!pip install xformers==0.0.24 --no-deps` and it work now

**Comment by noriwaru** [comment]
> i change xformers to `!pip install xformers==0.0.24 --no-deps` and it work now

It worked!　Thanks. I am very happy.
