### ISSUE TITLE
Is this just for anime?

### ISSUE THREAD

**Issue by DarkAlchy** [Linaqruf/kohya-trainer#36]
Since I can't get any info on how to run the notebook I made it to 3.3 and all the anime stuff it lost me.  Zip this or that etc...

Seriously, this needs an instructional video or at least something unless this is just for anime then I have no need or want of it.

**Comment by Linaqruf** [comment]
no? lol. what do you mean zip this and that means it for anime stuff? it's for easier upload and download cuz it will take time too upload and download your dataset one by one.

you can change pretrained model to something like original SD, open journey etc, put non anime dataset, set data annotation for blip only, and you're good.

**Comment by DarkAlchy** [comment]
Thanks as it was looking like it was for anime.
