### ISSUE TITLE
Error 403 Forbidden when trying to connect to Colab's server

### ISSUE THREAD

**Issue by DarkSolus** [Linaqruf/kohya-trainer#41]
![image](https://user-images.githubusercontent.com/110533261/215255873-5349d963-0cf8-4be6-86b0-6d2f583816c1.png)
So when I click on the localhost link, it is supposed to open File Explorer, but all I get is error 403. Any reason for that?

**Comment by Linaqruf** [comment]
you need to wait for a couple second to prepare the tunne, like webui in colab

**Comment by Linaqruf** [comment]
feel free to reopen this issue ticket
