### ISSUE TITLE
Create JSON file error: list index out of range

### ISSUE THREAD

**Issue by brandnewfakeuser** [Linaqruf/kohya-trainer#47]
In the LORA finetuner notebook.
I've used this successfully before, but with a smaller dataset.
Do I have too many images? tags too long?

/content/kohya-trainer/finetune
found 156 images.
new metadata will be created / 新しいメタデータファイルが作成されます
merge tags to metadata json.
 79% 124/156 [00:00<00:00, 39430.91it/s]
Traceback (most recent call last):
  File "merge_dd_tags_to_metadata.py", line 62, in <module>
    main(args)
  File "merge_dd_tags_to_metadata.py", line 35, in main
    tags = f.readlines()[0].strip()
IndexError: list index out of range

**Comment by Linaqruf** [comment]
probably tag list too long, or you can check tag in 124/156

**Comment by brandnewfakeuser** [comment]
I think it was actually something the filenames, but I'm not sure which one specifically caused the problem. I just renamed them all and that seemed to fix it. Thank you for the great work!
