### ISSUE TITLE
Need some help with all this step stuff and an Automatic1111 error.

### ISSUE THREAD

**Issue by GeneralAwareness** [Linaqruf/kohya-trainer#51]
I have been playing trying to get about 1200 steps but for some reason it isn't adding up.

![image](https://user-images.githubusercontent.com/124339252/216571572-58ed57ac-bd1f-4b04-be68-7e564799dbe0.png)

Judging by that (where 172 came from I do not know) 172 steps for 86 epochs which is over 14k total steps.

After my 300 step training I called it in Automatic1111 to get some weird image that was nothing like it should have been.  I then looked at the cli to get this - Failed to match keys when loading Lora D:\stable-diffusion-webui\models\Lora\Cry0n.safetensors  Cry0n being the model it created.

**Comment by Linaqruf** [comment]
LoRA? i thought you're training normal dreambooth? 
do you get output model with 2gb file size or 200mb one?

**Comment by GeneralAwareness** [comment]
200mb.  All of this is for Lora as I prefer to use Shiv's Dreambooth for entire 2gig models.

**Comment by Linaqruf** [comment]
also did u use the extension ?
i'm not recommend to use the built-in auto1111 lora implementation cuz i never use it

https://github.com/kohya-ss/sd-webui-additional-networks

**Comment by GeneralAwareness** [comment]
> also did u use the extension ? i'm not recommend to use the built-in auto1111 lora implementation cuz i never use it
> 
> https://github.com/kohya-ss/sd-webui-additional-networks

Can't use it on colab as it throws an error.  The entire DB extension on Colab is broken and he said it was not made for colab.

**Comment by Linaqruf** [comment]
no it's not db extension, https://github.com/kohya-ss/sd-webui-additional-networks is for loading lora model trained with her script and not to train one.

another question, did u train lora on sdv2 model?

built-in webui lora reported can't load lora trained from sdv2 model
![image](https://user-images.githubusercontent.com/50163983/216595113-bf63032a-e4fa-4d57-bee1-1695fea727d1.png)

**Comment by GeneralAwareness** [comment]
Yeah, I downloaded it and saw that about 2.x because this was trained in 2.x.  Does her script work with 2.x?

**Comment by Linaqruf** [comment]
certainly!

**Comment by GeneralAwareness** [comment]
Trying it now.

**Comment by GeneralAwareness** [comment]
How do I know if it worked because what I got back was nothing like I trained?

**Comment by Linaqruf** [comment]
you should see new section in below t2i/i2i tab, above script selection, there is section called additional network, enable that, then load your lora there

**Comment by GeneralAwareness** [comment]
I used it.  I called my model and got the same garbage back.  My colab free time is about up so when it comes back I will try her frog example and I better get a frog after her 640 training steps or I will 100% know something is broken.  For all I know all of this is broken for 2.x and all the titty people who never came to 2.x to use this we have no idea.

**Comment by GeneralAwareness** [comment]
I got a froggie so time to dig deeper later on to see if me, or 2.1.

**Comment by Linaqruf** [comment]
good luck!

**Comment by GeneralAwareness** [comment]
Thanks again.  Oh, btw, I managed to get the webgui version to run for 2.1 768x768 on 5.9GB

**Comment by Linaqruf** [comment]
oh good to hear that!

**Comment by GeneralAwareness** [comment]
Funny thing is I came back tonight with the same everything and OOM.  No idea why.

**Comment by Linaqruf** [comment]
Maybe batch size too high, try lowering the batch size

**Comment by GeneralAwareness** [comment]
As I said above nothing changed it was the same.  btw, LoRA will not train on 2.x unless your card has BF16 which mine doesn't, nor does the T4 on Colab.  IOW, LoRA is dead for a lot of people.  I had a couple of friends try on their x090 cards and wonderful results then I had them try with fp16, and float, and nope 100% rubbish.  fp16 DOES work with SD 1.x though.

**Comment by Linaqruf** [comment]
Interesting, thanks for reporting in,
I'll try to train LoRA in SD v2.1

**Comment by Wawaworker** [comment]
Training in 2.1 works for me, but only on the T4. Seems like an former issue occurs when I load up the A1000 colab
