### ISSUE TITLE
Why is there no "--keep_tokens" field?

### ISSUE THREAD

**Issue by noriwaru** [Linaqruf/kohya-trainer#54]
Sorry for the trivial question. Is it because of some problem that there is no above item in the "Kohya LoRA Dreambooth" notebook?
Would work if I add myself "--keep_tokens=1 \" in the cell "5.3. Start LoRA Dreambooth"?

**Comment by Linaqruf** [comment]
yea, feel free to add that in additional argument field, but dont separating by commas
i dont think if you need to keep tokens in dreambooth, cuz you got instance prompt already

**Comment by noriwaru** [comment]
https://github.com/kohya-ss/sd-scripts/blob/main/train_db_README-ja.md

Last item
>>Using captions in DreamBooth
「If you place a file with the same filename as the image and with a .caption extension (which can be optionally changed) in the folder of training and regularization images, DreamBooth will read the caption from that file and train it as a prompt.
The folder name (identifier class) will no longer be used to learn those images.
You may want to caption each image (using BLIP, etc.) to better identify the attributes you wish to learn.」

Reading the above, I think you need to write the instance prompt in the .txt file. I am not sure if the instance prompt has to be written at the beginning of the sentence to be effective... but if you shuffle the tags, the instance prompt will also be shuffled and not always at the beginning of the sentence, making it less effective. That's why keep_tokens is needed... I have heard. I don't know if that is true or not.

**Comment by Linaqruf** [comment]
instance prompt for dreambooth is token you created in the foldername
`<repeats>_<token> <class>`
for example
`10_sks frog`

And the training script will use that `token` for learning. if you add caption, `token` will no longer be used for learning but doesn't mean it turned useless. The token still remain to be instance prompt for generating model with your lora/dreambooth.

**Comment by noriwaru** [comment]
I see, I understand. And thanks for adding "--keep_tokes".
