### ISSUE TITLE
Will this adapt to local server(conda is best),not just colab?

### ISSUE THREAD

**Issue by mio2333** [Linaqruf/kohya-trainer#6]
Firstly I should say, the project is excellent! Anything model is commonly used by so many people.

Because you can not train model too much time (for example,30000 steps of training will take 17 hours) in Colab, and Colab needs to keep the browser open,so will this project adapt to local server?

**Comment by Linaqruf** [comment]
you can just copy paste the code to jupyter notebook and do some tweak, i'm also using this trainer on kaggle/sagemaker and it works well

i suggest you to do max 10k training per session and save last ckpt+last state so that you can resume your training next time.
