### ISSUE TITLE
please explain native vs dreambooth

### ISSUE THREAD

**Issue by maxixa** [Linaqruf/kohya-trainer#61]
what is pros and cons between two of them?
why one should chooce one over the other?

**Comment by Linaqruf** [comment]
Native:
- flexible for larger dataset and longer training if you want to process 1000-100k dataset
- is a traditional fine-tuning and common training method in Machine Learning
- you can train with both captions and tags by defining JSON file 
- not training text encoder by default
- bucketing and cache latents using separate script
- you don't need to set instance prompt, so useful for style training
- you dont need to set <number_of_repeats>_<token> <class> to your foldername like dreambooth
Dreambooth
- for short training
- is a native fine-tuning but for specific use, such as training object or style
- `prior_loss_weight = 1.0`
- training with text encoder by default
- use dreambooth when you want to avoid training with captions (but you can train with captions in kohyas)
- you're training with instance token in dreambooth, eg. `sksbiden` for training Joe Biden dreambooth, and you need to write `sksbiden` as a prompt 
- you can only train with 1 type of caption at a time, e.g. only .txt or .caption
- useful for multi-styled training e.g. Nitrosocke Diffusion, you can train with multiple folder and object in 1 session
- you can use reg images to prevent overfitting 

Use dreambooth when u wanna train on style or object
Use native when u wanna 'resuming' a model training with your own dataset
