### ISSUE TITLE
Xformers for A100

### ISSUE THREAD

**Issue by Wawaworker** [Linaqruf/kohya-trainer#62]
Can you help me locate the proper code in order to run the notebook on the colab + GPU models

I believe I will need a precompiled xformers wheel.

**Comment by Linaqruf** [comment]
sure

install this one for A100
%pip install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15+e163309.d20230103.ColabProA100-cp38-cp38-linux_x86_64.whl

**Comment by Linaqruf** [comment]
i will use this for the next update so i if it's detect A100 it will install xformers wheels for A100 instead
```
  s = getoutput('nvidia-smi')
  if install_xformers:
    if 'T4' in s:
      %pip -q install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.16/xformers-0.0.16+814314d.d20230118-cp38-cp38-linux_x86_64.whl
      !pip -q install --pre triton
    if 'A100' in s:
      %pip -q install https://github.com/camenduru/stable-diffusion-webui-colab/releases/download/0.0.15/xformers-0.0.15+e163309.d20230103.ColabProA100-cp38-cp38-linux_x86_64.whl
```

But you need to wait for people compiling xformers 16 for A100
