### ISSUE TITLE
Image does not have a caption even though I used waifu diffusion auto tagger

### ISSUE THREAD

**Issue by AnANTKA** [Linaqruf/kohya-trainer#63]
here is what it looks like

![image](https://user-images.githubusercontent.com/52686181/217156994-4dc522cc-55b0-4b9f-84ce-2be32aa8c4c6.png)

I am new to this and I don't get why it isn't detecting that there are captions

**Comment by AnANTKA** [comment]
It isn't even generating the captions
I realized this after posting this. How do I make it generate the .caption files?

**Comment by Linaqruf** [comment]
It's not error, you just dont have .caption files, you can pass if you dont need them or already has tags

you can generating `.caption` by running this cell:
![image](https://user-images.githubusercontent.com/50163983/217429613-0010a118-8cde-4563-b428-a571a09fadbc.png)

**Comment by Linaqruf** [comment]
No problem, sorry for the late answer!
