### ISSUE TITLE
Kohya LoRA for styles.

### ISSUE THREAD

**Issue by GeneralAwareness** [Linaqruf/kohya-trainer#64]
I noticed the DB Lora trainer extension for auto1111 has styles where it turns off prior preservation, but how do I do styles with this, AND how would I even call the style?  Used to the TI way of doing styles, though that doesn't seem to be working with this.

**Comment by Linaqruf** [comment]
I suggest to use LoRA finetuning notebook if you want to train without prior loss weight and train for style
But you can still using LoRA dreambooth to train style, in the end it depends on your liking

Personally I use finetuning notebook to train LoRA so i dont need to use trigger token like dreambooth.

**Comment by Linaqruf** [comment]
I'm sorry for late reply

**Comment by GeneralAwareness** [comment]
> I'm sorry for late reply

No worries.  I don't like finetuning because I am using around 4-30 images (depends what it is and how many I can get of it).  Finetuning those people use 75k-500k images.

**Comment by GeneralAwareness** [comment]
With TI I am used to "in the style of <emb>" but with this LoRA how would I call it?  I did do a training with no reg images but I can't style anything with it as it still made a subject I think.

**Comment by Fannovel16** [comment]
> > I'm sorry for late reply
> 
> No worries. I don't like finetuning because I am using around 4-30 images (depends what it is and how many I can get of it). Finetuning those people use 75k-500k images.

Kohya-LoRA-finetuner isn't "finetuning", it is very like Kohya-LoRA-Dreambooth. Differences between it with LoRA DB are:
- Different dataset folder system
- Don't have reg images options
- Is suitable for one dataset
- Export json file which contains metadata about the dataset

**Comment by GeneralAwareness** [comment]
Sounds like the LoRA finetuning may be more appropriate for styles and the DB method for subjects/objects?

**Comment by Fannovel16** [comment]
No, they are basically the same. The main difference is that LoRA finetuner is more suitable for single concept training due to the directory system.

**Comment by GeneralAwareness** [comment]
> No, they are basically the same. The main difference is that LoRA finetuner is more suitable for single concept training due to the directory system.

Yes, after playing with both I decided to stick with the DB method as I can always add more concepts if I ever wish too, and I just leave the reg directory empty to achieve the same result.
