### ISSUE TITLE
Mixup between `remove_words` and `undesired_words` during GIT Captioning

### ISSUE THREAD

**Issue by MasterScrat** [Linaqruf/kohya-trainer#69]
I believe there's a confusion in cell "4.4.1. GIT Captioning": 

- `make_captions_by_git.py` expects a boolean for `args.remove_words`:

```python
  parser.add_argument("--remove_words", action="store_true",
                      help="remove like `with the words xxx` from caption / `with the words xxx`のような部分をキャプションから削除する")
```

Used here: https://github.com/Linaqruf/kohya-trainer/blob/main/finetune/make_captions_by_git.py#L86

- However the notebook makes it look like you can input `undesired_words` as a string. As a result the option `args.remove_words` is always enabled and the input string is not used.

**Comment by Linaqruf** [comment]
Thank you, I will fix that
