### ISSUE TITLE
Error Lora Dreambooth

### ISSUE THREAD

**Issue by cdefghijkl** [Linaqruf/kohya-trainer#70]
When I start training this error always happened since yesterday no matter what settings I tried:

![Screenshot 2023-02-09 at 03-32-13 Google Colaboratory](https://user-images.githubusercontent.com/121331850/217646319-f2d43f11-b69b-4ef3-a92b-00fe6e7a05b6.png)

**Comment by MusaPar** [comment]
I got the same error (the last line ended with `<Signals.SIGKILL: 9>`), looks like it didn't have enough memory for 7.7GB SD1.5.
I tried another smaller model and it works fine.

**Comment by cdefghijkl** [comment]
I use the one from preset dropdown list, it is pruned-emaonly.

**Comment by cdefghijkl** [comment]
So I tried download the model pruned-emaonly.safetensors use custom model cell and it works now no error.

**Comment by Linaqruf** [comment]
Thanks for the feedback, I will consider to change the model to safetensors for the next update
