### ISSUE TITLE
Auto captioning for images

### ISSUE THREAD

**Issue by Gyro0o** [Linaqruf/kohya-trainer#71]
Can you please add auto captioning for images names
ex: jennaortg.png would be captioned directly as "jennaortg" prompt in the txt or captions file.

**Comment by Fannovel16** [comment]
You can use cell 4.4.3. Insert Custom Caption/Tag to do it.

**Comment by Gyro0o** [comment]
Yes but I have to run caption or tag the image before which takes time

**Comment by IcelandicIcecream** [comment]
%cd {train_data_dir} 
for training_file in os.listdir():
    if ".caption" in training_file:
      new_caption = concept_name + " " + open(training_file).read()
      open(training_file, "w").write(new_caption)
      print(open(training_file).read())
      
I added this at the bottom of the GIT Captioning section. It basically adds the concept name to the front of the auto-generated caption.

**Comment by Linaqruf** [comment]
Hi, I'm included this feature in the latest update, if no `.txt` or `.caption` detected in `train_data_dir` it will create new empty caption files
1. I also fix the bug when `image..txt` is created with additional `( . )`
2. I also improved how to add caption and tags
3. I also added an abillity to remove tags
Thank you, and sorry for the very late reply
