### ISSUE TITLE
Finetuning sd-v2-depth models?

### ISSUE THREAD

**Issue by 0x1355** [Linaqruf/kohya-trainer#75]
Is it possible to fine-tune the v2-depth model? I searched on the repo but couldn't find an answer. Thanks.

**Comment by Linaqruf** [comment]
Greetings,
Unfortunately no, but you can try to request a feature in the main repo, I think Kohya will be happy to help
https://github.com/kohya-ss/sd-scripts

Or you can try this one for finetune an inpainting model or v2-depth model
https://github.com/devilismyfriend/StableTuner

**Comment by 0x1355** [comment]
StableTuner seems to meet my needs. Thank you for the pointer!
