### ISSUE TITLE
Could this trick be implemented ?

### ISSUE THREAD

**Issue by Njbx** [Linaqruf/kohya-trainer#76]
Fine-tuning against a modified noise, enables Stable Diffusion to generate very dark or light images easily.

More information
https://www.crosslabs.org/blog/diffusion-with-offset-noise

**Comment by Linaqruf** [comment]
I think it's possible 
![image](https://user-images.githubusercontent.com/50163983/218376053-6f33d300-0e08-4542-8ca8-3eb6fe78738d.png)

we need to change that code to this 
```
noise = torch.randn_like(latents) + 0.1 * torch.randn(latents.shape[0], latents.shape[1], 1, 1)
```

**Comment by GeneralAwareness** [comment]
In which file?  btw, the noise stuff is really just doing a contrast fix not a real light/dark fix as SD *WILL* insert a big ass lightbulb on you if the scene goes too dark (happened to me many times) but only with 2.x generates.

**Comment by GeneralAwareness** [comment]
I tried that and it would not run.  Maybe because it is missing the device?

**Comment by GeneralAwareness** [comment]
noise = torch.randn_like(latents) + 0.1 * torch.randn(latents.shape[0], latents.shape[1], 1, 1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by Njbx** [comment]
> noise = torch.randn_like(latents) + 0.1 * torch.randn(latents.shape[0], latents.shape[1], 1, 1)

noise = torch.randn_like(latents, device=latents.device) + 0.1 * torch.randn(latents.shape[0], latents.shape[1], 1, 1, device=latents.device)

**Comment by GeneralAwareness** [comment]
> > noise = torch.randn_like(latents) + 0.1 * torch.randn(latents.shape[0], latents.shape[1], 1, 1)
> 
> `noise = torch.randn_like(latents, device=latents.device) + 0.1 * torch.randn(latents.shape[0], latents.shape[1], 1, 1, device=latents.device)`

Thank you as I tried that a different way that didn't work.  Later I will try it that way as that looks like it should work.

I wonder the suggestion was 0.1 from Kohya but what happens to the result if we change that to a different value?

Thank you again.

**Comment by Linaqruf** [comment]
added `--noise_offset` to the notebook in the new update, i'm closing this issue, feel free to open this issue again.

**Comment by rexelbartolome** [comment]
@GeneralAwareness hey, do you have any recommendations for noise offset? I want to try it out too but too afraid of what will happen. im training a model but it's taking 1hr 30min to finish (170 or so images)

**Comment by GeneralAwareness** [comment]
@rexelbartolome I no longer use it as I never had as much success with it as others seem to.  I know as soon as I used it you have to lower you LRs and still the loss would go up by .1-.2.  .1 was way too strong for most datasets too.

**Comment by rexelbartolome** [comment]
> .1 was way too strong for most datasets too.
can you explain what you mean by this @GeneralAwareness ? Sorry if this is getting out of topic. I only stick to the default settings. And yea I tested it out with a smaller dataset with 0.01 noise offset and it showed a loss of 0.117. I'm currently using the lora finetuner if that helps

**Comment by Linaqruf** [comment]
It's recommended to use 0.1 for noise offset
Kohya and this article said that

https://www.crosslabs.org/blog/diffusion-with-offset-noise

**Comment by rexelbartolome** [comment]
> It's recommended to use 0.1 for noise offset Kohya and this article said that
I see, thanks. But what about the loss? why is it a bad thing that it goes up to .2?
