### ISSUE TITLE
I didn't get what is the 'Native Training', is that the way same with ldm?

### ISSUE THREAD

**Issue by Alfred-Duncan** [Linaqruf/kohya-trainer#79]
Is that the 'Native Training' way same with ldm? I mean training the model with whole weight, like stablity and compvis do. 
I have lots of 3090 graphics card and I'm looking for a easy and good way to train my own model. (With a have a large and detailed dataset in my professional field)

**Comment by Linaqruf** [comment]
Yes it's the same as finetune, training with captions, you train full model, you get full model.
