### ISSUE TITLE
About dreambooth reg image

### ISSUE THREAD

**Issue by mio2333** [Linaqruf/kohya-trainer#8]
Not a technical problem, but about dreambooth train setting.
1. The project uses girl images from [waifu-research-department](https://huggingface.co/waifu-research-department),which are some images generated by Waifu Diffusion 1.3 (and I think it's not a high-quality dataset). Is this ok? Because in the original dreambooth algorithm the regulation images are generated from the trained model.
2. Setting config as folder name seems not a good method, for example if the instance prompt or class prompts are multi Danbooru style, like "1girl,solo,white hair". The project can not accept this setting.
3. Could the trainer generate test image while training? It will be better for selecting model rather than checking every model after finishing training?

I can fix the above questions by changing the code but I'm afraid that It will conflict with your updates. So I hope you can take them into consideration,thanks!

**Comment by Linaqruf** [comment]
Sorry for the late reply, I don't check the issue tab very often.

1. I already added a function to generate reg_images using Kohya's gen_img_diffusers.py in the kohya-dreambooth repo, but it's worth mentioning that I haven't checked the latest version of dreambooth. It may not be integrated with the latest script updates by Kohya and the latest repo format.
2. The backend is Kohya's script and I haven't touched it myself. I just created the Colab UI. However, I suggest using the tagger/captionin to give labels to the dataset, similar to the finetune process. Just rename the folder with the desired instance prompt or concept to use it with dreambooth.
3. I don't think training the unet would work like that, as it's a process for textual inversion. But I also added Kohya's gen_img_diffusers below the training cell, so you can try your trained model after training.

Feel free to change my code. You can also fork it and create your own repo.
