### ISSUE TITLE
FATAL: this function is for sm80, but was built for sm750

### ISSUE THREAD

**Issue by MushroomFleet** [Linaqruf/kohya-trainer#85]
Hi There, i used your Colab Fine Tuning to build 108 separate datasets into one LORA, around 4200 images in total.
Thanks for all your hard work! I am overjoyed by the results from using the Fine Tuning Colab

I had some errors, 
"FATAL: this function is for sm80, but was built for sm750"
and had to add some code under section 1.2:
```
!pip install ninja
# Set TORCH_CUDA_ARCH_LIST if running and building on different GPU types
!pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
```
![image](https://user-images.githubusercontent.com/7318371/219548955-66c028c3-8094-4c3c-be3a-5c77ff62faf9.png)

This allows me to complete my model training
I'm sure you know a better way to make use of this

**Comment by Linaqruf** [comment]
Thanks for the suggestion, and sorry for the late reply. I added xformers precompiled wheels for A100 in the new update. I'm closing this Issue, let me know if you facing the error again.

**Comment by ride5k** [comment]
had this same issue, can confirm resolved with new build
