### ISSUE TITLE
Problem when running training cell

### ISSUE THREAD

**Issue by JJJ-art111** [Linaqruf/kohya-trainer#87]
Getting this error message when i run the training cell. 

OSError: [Errno 95] Operation not supported: '/content/drive/dreambooth_lora_cmd.yaml

what am i missing?

**Comment by Linaqruf** [comment]
I fixed it in the new update, I'm sorry for the late reply

This is update logs for today:
```
- Fixing bugs when output_dir located in google drive, it assert an error because of something like /content/drive/dreambooth_cmd.yaml which is forbidden, now instead of saved to {output_dir}, now training args history are saved to {training_dir}
```

**Comment by Linaqruf** [comment]
I close this issue for now, let me know if you facing the same error again, feel free to reopen this issue!
