### ISSUE TITLE
Could this work without an Nvidia GPU? Would it work on my M1 Mac?

### ISSUE THREAD

**Issue by YousufSSyed** [Linaqruf/kohya-trainer#91]
I've been using the Colab notebook but availability of Colab varies, and I've had issues with it running out of RAM. It would be great if there a Kaggle notebook for this, since GPU and service availability is consistent. Otherwise, I would try to run it on my 16'' MBP (M1 Pro, base model).

**Comment by Linaqruf** [comment]
You need VRAM, while MAC doesn't have that, iirc. Also this script probably only works on windows, and linux.

**Comment by YousufSSyed** [comment]
Alright, could you look at my issue with the colab notebook?
https://github.com/Linaqruf/kohya-trainer/issues/96
