### ISSUE TITLE
Textual inversion

### ISSUE THREAD

**Issue by Rudy34160** [Linaqruf/kohya-trainer#92]
Do we know if the Colab for textual inversion is in progress? I can't wait to try it!!

**Comment by GeneralAwareness** [comment]
If it gets implemented then I will no longer need to use Automatic1111 on colab.

**Comment by Linaqruf** [comment]
I'm sorry but i cancellet the project for now,
It's in the readme
___
- Kohya Textual Inversion are cancelled for now, because maintaining 4 Colab Notebook already making me this tired. 
  - Please use this instead, not kohya script but everyone on WD server using this since last year:
    - [stable-textual-inversion-cafe colab](https://colab.research.google.com/drive/1bbtGmH0XfQWzVKROhiIP8x5EAv6XuohJ) 
    - [stable-textual-inversion-cafe Colab - Lazy Edition](https://colab.research.google.com/drive/1ouTImTpYkBrX5hiVWrzJeFtOyKES92uV)
